spring:
  application:
   name: ORDER-SERVER
  config:
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full


server:
  port : 4001

feign:
  client:
    config:
      default:
        loggerLevel: full


resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

